void main(){
    int n1=9;
    int n2=7;
    // int r=n1%n2;
    // print("result=${r}");
    // bool f=n1>10 && n2>20;
    //  print(f);
    print(n1++);
     print(n1);
    print(n1--);
     print(n1);
    print(--n1);
     print(n1);
    print(++n2);
     print(n2);
    bool g=n1>10 || n2>20;
     print(g);
    n1+=10;
     print(n1);
     n1-=10;
     print(n1);
     n1*=10;
     print(n1);
     //n1/=10;
     //print(n1);
     int n=4;
     print(++n);
     print(n+=10);
     double r=n/10;
     print(r);
}